### ISSUE TITLE
[IRRELEVANT]: Intento fallido de contactar contigo con la intencion de resolver una duda.

### ISSUE THREAD

**Issue by LagrangianLad** [ranon-rat/ranon-rat.github.io#1]
¡Buenos días!
He intentado ponerme en contacto contigo, utilizando el id de Discord que has proporcionado para que me **resuelvas una pequeña duda que tengo acerca del código de uno de tus proyectos**.

Parece que **no aceptas solicitudes de amistad en Discord**. ¿Hay alguna otra forma de contactarte?, quizás un mail o tu nombre de usuario en otra plataforma...

Gracias de antemano.

**Comment by ranon-rat** [comment]
ya solucione eso , perdone la incumbencia

**Comment by ranon-rat** [comment]
tambien puede contactarme a traves de twitter o a traves de instagram https://www.instagram.com/nodejs_boy/ https://twitter.com/ranon_rat , luego lo agregare a la pagina
